package Mapping;
// Generated 8 févr. 2020 15:26:40 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * AffecterId generated by hbm2java
 */
public class AffecterId  implements java.io.Serializable {


     private int codeprog;
     private int codecli;
     private Date dateaff;

    public AffecterId() {
    }

    public AffecterId(int codeprog, int codecli, Date dateaff) {
       this.codeprog = codeprog;
       this.codecli = codecli;
       this.dateaff = dateaff;
    }
   
    public int getCodeprog() {
        return this.codeprog;
    }
    
    public void setCodeprog(int codeprog) {
        this.codeprog = codeprog;
    }
    public int getCodecli() {
        return this.codecli;
    }
    
    public void setCodecli(int codecli) {
        this.codecli = codecli;
    }
    public Date getDateaff() {
        return this.dateaff;
    }
    
    public void setDateaff(Date dateaff) {
        this.dateaff = dateaff;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AffecterId) ) return false;
		 AffecterId castOther = ( AffecterId ) other; 
         
		 return (this.getCodeprog()==castOther.getCodeprog())
 && (this.getCodecli()==castOther.getCodecli())
 && ( (this.getDateaff()==castOther.getDateaff()) || ( this.getDateaff()!=null && castOther.getDateaff()!=null && this.getDateaff().equals(castOther.getDateaff()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCodeprog();
         result = 37 * result + this.getCodecli();
         result = 37 * result + ( getDateaff() == null ? 0 : this.getDateaff().hashCode() );
         return result;
   }   


}


