package Mapping;
// Generated 8 févr. 2020 15:26:40 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Affecter generated by hbm2java
 */
public class Affecter  implements java.io.Serializable {

    @Override
    public int hashCode() {
        return super.hashCode(); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public boolean equals(Object obj) {
        return super.equals(obj); //To change body of generated methods, choose Tools | Templates.
    }


     private AffecterId id;
     private Client client;
     private Programme programme;
     private Date datefinaff;
     private String statutaff;

    public Affecter() {
    }

	
    public Affecter(AffecterId id, Client client, Programme programme) {
        this.id = id;
        this.client = client;
        this.programme = programme;
    }
    public Affecter(AffecterId id, Client client, Programme programme, Date datefinaff, String statutaff) {
       this.id = id;
       this.client = client;
       this.programme = programme;
       this.datefinaff = datefinaff;
       this.statutaff = statutaff;
    }
   
    public AffecterId getId() {
        return this.id;
    }
    
    public void setId(AffecterId id) {
        this.id = id;
    }
    public Client getClient() {
        return this.client;
    }
    
    public void setClient(Client client) {
        this.client = client;
    }
    public Programme getProgramme() {
        return this.programme;
    }
    
    public void setProgramme(Programme programme) {
        this.programme = programme;
    }
    public Date getDatefinaff() {
        return this.datefinaff;
    }
    
    public void setDatefinaff(Date datefinaff) {
        this.datefinaff = datefinaff;
    }
    public String getStatutaff() {
        return this.statutaff;
    }
    
    public void setStatutaff(String statutaff) {
        this.statutaff = statutaff;
    }




}


