package Mapping;
// Generated 8 févr. 2020 15:26:40 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Coach generated by hbm2java
 */
public class Coach  implements java.io.Serializable {


     private Integer idcoach;
     private User user;
     private String nomcoach;
     private String prenomcoach;
     private Date datenaisscoach;
     private Character sexecoach;

    public Coach() {
    }

    public Coach(User user, String nomcoach, String prenomcoach, Date datenaisscoach, Character sexecoach) {
       this.user = user;
       this.nomcoach = nomcoach;
       this.prenomcoach = prenomcoach;
       this.datenaisscoach = datenaisscoach;
       this.sexecoach = sexecoach;
    }
   
    public Integer getIdcoach() {
        return this.idcoach;
    }
    
    public void setIdcoach(Integer idcoach) {
        this.idcoach = idcoach;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getNomcoach() {
        return this.nomcoach;
    }
    
    public void setNomcoach(String nomcoach) {
        this.nomcoach = nomcoach;
    }
    public String getPrenomcoach() {
        return this.prenomcoach;
    }
    
    public void setPrenomcoach(String prenomcoach) {
        this.prenomcoach = prenomcoach;
    }
    public Date getDatenaisscoach() {
        return this.datenaisscoach;
    }
    
    public void setDatenaisscoach(Date datenaisscoach) {
        this.datenaisscoach = datenaisscoach;
    }
    public Character getSexecoach() {
        return this.sexecoach;
    }
    
    public void setSexecoach(Character sexecoach) {
        this.sexecoach = sexecoach;
    }

 @Override
    public int hashCode() {
        return super.hashCode(); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public boolean equals(Object obj) {
        return super.equals(obj); //To change body of generated methods, choose Tools | Templates.
    }


}


