package Mapping;
// Generated 8 févr. 2020 15:26:40 by Hibernate Tools 4.3.1



/**
 * ComposerCircuit generated by hbm2java
 */
public class ComposerCircuit  implements java.io.Serializable {


     private ComposerCircuitId id;
     private Circuit circuit;
     private Exercice exercice;
     private Integer ordreexocir;
     private int repetiminexo;

    public ComposerCircuit() {
    }

	
    public ComposerCircuit(ComposerCircuitId id, Circuit circuit, Exercice exercice, int repetiminexo) {
        this.id = id;
        this.circuit = circuit;
        this.exercice = exercice;
        this.repetiminexo = repetiminexo;
    }
    public ComposerCircuit(ComposerCircuitId id, Circuit circuit, Exercice exercice, Integer ordreexocir, int repetiminexo) {
       this.id = id;
       this.circuit = circuit;
       this.exercice = exercice;
       this.ordreexocir = ordreexocir;
       this.repetiminexo = repetiminexo;
    }
   
    public ComposerCircuitId getId() {
        return this.id;
    }
    
    public void setId(ComposerCircuitId id) {
        this.id = id;
    }
    public Circuit getCircuit() {
        return this.circuit;
    }
    
    public void setCircuit(Circuit circuit) {
        this.circuit = circuit;
    }
    public Exercice getExercice() {
        return this.exercice;
    }
    
    public void setExercice(Exercice exercice) {
        this.exercice = exercice;
    }
    public Integer getOrdreexocir() {
        return this.ordreexocir;
    }
    
    public void setOrdreexocir(Integer ordreexocir) {
        this.ordreexocir = ordreexocir;
    }
    public int getRepetiminexo() {
        return this.repetiminexo;
    }
    
    public void setRepetiminexo(int repetiminexo) {
        this.repetiminexo = repetiminexo;
    }

 @Override
    public int hashCode() {
        return super.hashCode(); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public boolean equals(Object obj) {
        return super.equals(obj); //To change body of generated methods, choose Tools | Templates.
    }


}


