package Mapping;
// Generated 8 févr. 2020 15:26:40 by Hibernate Tools 4.3.1



/**
 * ComposerSeance generated by hbm2java
 */
public class ComposerSeance  implements java.io.Serializable {


     private ComposerSeanceId id;
     private Exercice exercice;
     private Seance seance;
     private Integer ordreexoseance;

    public ComposerSeance() {
    }

	
    public ComposerSeance(ComposerSeanceId id, Exercice exercice, Seance seance) {
        this.id = id;
        this.exercice = exercice;
        this.seance = seance;
    }
    public ComposerSeance(ComposerSeanceId id, Exercice exercice, Seance seance, Integer ordreexoseance) {
       this.id = id;
       this.exercice = exercice;
       this.seance = seance;
       this.ordreexoseance = ordreexoseance;
    }
   
    public ComposerSeanceId getId() {
        return this.id;
    }
    
    public void setId(ComposerSeanceId id) {
        this.id = id;
    }
    public Exercice getExercice() {
        return this.exercice;
    }
    
    public void setExercice(Exercice exercice) {
        this.exercice = exercice;
    }
    public Seance getSeance() {
        return this.seance;
    }
    
    public void setSeance(Seance seance) {
        this.seance = seance;
    }
    public Integer getOrdreexoseance() {
        return this.ordreexoseance;
    }
    
    public void setOrdreexoseance(Integer ordreexoseance) {
        this.ordreexoseance = ordreexoseance;
    }


 @Override
    public int hashCode() {
        return super.hashCode(); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public boolean equals(Object obj) {
        return super.equals(obj); //To change body of generated methods, choose Tools | Templates.
    }

}


