package Mapping;
// Generated 8 févr. 2020 15:26:40 by Hibernate Tools 4.3.1



/**
 * ComposerSeanceId generated by hbm2java
 */
public class ComposerSeanceId  implements java.io.Serializable {


     private int codeseance;
     private int codeexo;

    public ComposerSeanceId() {
    }

    public ComposerSeanceId(int codeseance, int codeexo) {
       this.codeseance = codeseance;
       this.codeexo = codeexo;
    }
   
    public int getCodeseance() {
        return this.codeseance;
    }
    
    public void setCodeseance(int codeseance) {
        this.codeseance = codeseance;
    }
    public int getCodeexo() {
        return this.codeexo;
    }
    
    public void setCodeexo(int codeexo) {
        this.codeexo = codeexo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ComposerSeanceId) ) return false;
		 ComposerSeanceId castOther = ( ComposerSeanceId ) other; 
         
		 return (this.getCodeseance()==castOther.getCodeseance())
 && (this.getCodeexo()==castOther.getCodeexo());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCodeseance();
         result = 37 * result + this.getCodeexo();
         return result;
   }   


}


