package Mapping;
// Generated 8 févr. 2020 15:26:40 by Hibernate Tools 4.3.1

import java.util.Objects;




/**
 * ComposerSeance generated by hbm2java
 */
public class ComposerSeance  implements java.io.Serializable {


     private ComposerSeanceId id;
     private Exercice exercice;
     private Seance seance;
     private Integer ordreexoseance;

    public ComposerSeance() {
    }

	
    public ComposerSeance(ComposerSeanceId id, Exercice exercice, Seance seance) {
        this.id = id;
        this.exercice = exercice;
        this.seance = seance;
    }
    public ComposerSeance(ComposerSeanceId id, Exercice exercice, Seance seance, Integer ordreexoseance) {
       this.id = id;
       this.exercice = exercice;
       this.seance = seance;
       this.ordreexoseance = ordreexoseance;
    }
   
    public ComposerSeanceId getId() {
        return this.id;
    }
    
    public void setId(ComposerSeanceId id) {
        this.id = id;
    }
    public Exercice getExercice() {
        return this.exercice;
    }
    
    public void setExercice(Exercice exercice) {
        this.exercice = exercice;
    }
    public Seance getSeance() {
        return this.seance;
    }
    
    public void setSeance(Seance seance) {
        this.seance = seance;
    }
    public Integer getOrdreexoseance() {
        return this.ordreexoseance;
    }
    
    public void setOrdreexoseance(Integer ordreexoseance) {
        this.ordreexoseance = ordreexoseance;
    }

    @Override
    public int hashCode() {
        int hash = 5;
        hash = 79 * hash + Objects.hashCode(this.id);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final ComposerSeance other = (ComposerSeance) obj;
        if (!Objects.equals(this.id, other.id)) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "ComposerSeance{" + "id=" + id + ", exercice=" + exercice + ", ordreexoseance=" + ordreexoseance + '}';
    }


 

}


