package Mapping;
// Generated 8 févr. 2020 15:26:40 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Evaluer generated by hbm2java
 */
public class Evaluer  implements java.io.Serializable {


     private EvaluerId id;
     private Client client;
     private OccurrenceS occurrenceS;
     private Date dateeval;
     private String bras;
     private String poitrine;
     private String taille;
     private String hanches;
     private String cuisses;
     private Double cinqminallong;
     private Double apresflexion;
     private Double uneminallong;

    public Evaluer() {
    }

	
    public Evaluer(EvaluerId id, Client client, OccurrenceS occurrenceS) {
        this.id = id;
        this.client = client;
        this.occurrenceS = occurrenceS;
    }
    public Evaluer(EvaluerId id, Client client, OccurrenceS occurrenceS, Date dateeval, String bras, String poitrine, String taille, String hanches, String cuisses, Double cinqminallong, Double apresflexion, Double uneminallong) {
       this.id = id;
       this.client = client;
       this.occurrenceS = occurrenceS;
       this.dateeval = dateeval;
       this.bras = bras;
       this.poitrine = poitrine;
       this.taille = taille;
       this.hanches = hanches;
       this.cuisses = cuisses;
       this.cinqminallong = cinqminallong;
       this.apresflexion = apresflexion;
       this.uneminallong = uneminallong;
    }
   
    public EvaluerId getId() {
        return this.id;
    }
    
    public void setId(EvaluerId id) {
        this.id = id;
    }
    public Client getClient() {
        return this.client;
    }
    
    public void setClient(Client client) {
        this.client = client;
    }
    public OccurrenceS getOccurrenceS() {
        return this.occurrenceS;
    }
    
    public void setOccurrenceS(OccurrenceS occurrenceS) {
        this.occurrenceS = occurrenceS;
    }
    public Date getDateeval() {
        return this.dateeval;
    }
    
    public void setDateeval(Date dateeval) {
        this.dateeval = dateeval;
    }
    public String getBras() {
        return this.bras;
    }
    
    public void setBras(String bras) {
        this.bras = bras;
    }
    public String getPoitrine() {
        return this.poitrine;
    }
    
    public void setPoitrine(String poitrine) {
        this.poitrine = poitrine;
    }
    public String getTaille() {
        return this.taille;
    }
    
    public void setTaille(String taille) {
        this.taille = taille;
    }
    public String getHanches() {
        return this.hanches;
    }
    
    public void setHanches(String hanches) {
        this.hanches = hanches;
    }
    public String getCuisses() {
        return this.cuisses;
    }
    
    public void setCuisses(String cuisses) {
        this.cuisses = cuisses;
    }
    public Double getCinqminallong() {
        return this.cinqminallong;
    }
    
    public void setCinqminallong(Double cinqminallong) {
        this.cinqminallong = cinqminallong;
    }
    public Double getApresflexion() {
        return this.apresflexion;
    }
    
    public void setApresflexion(Double apresflexion) {
        this.apresflexion = apresflexion;
    }
    public Double getUneminallong() {
        return this.uneminallong;
    }
    
    public void setUneminallong(Double uneminallong) {
        this.uneminallong = uneminallong;
    }


 @Override
    public int hashCode() {
        return super.hashCode(); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public boolean equals(Object obj) {
        return super.equals(obj); //To change body of generated methods, choose Tools | Templates.
    }

}


