package Mapping;
// Generated 8 févr. 2020 15:26:40 by Hibernate Tools 4.3.1



/**
 * EvaluerId generated by hbm2java
 */
public class EvaluerId  implements java.io.Serializable {


     private int codeoccs;
     private int codecli;

    public EvaluerId() {
    }

    public EvaluerId(int codeoccs, int codecli) {
       this.codeoccs = codeoccs;
       this.codecli = codecli;
    }
   
    public int getCodeoccs() {
        return this.codeoccs;
    }
    
    public void setCodeoccs(int codeoccs) {
        this.codeoccs = codeoccs;
    }
    public int getCodecli() {
        return this.codecli;
    }
    
    public void setCodecli(int codecli) {
        this.codecli = codecli;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof EvaluerId) ) return false;
		 EvaluerId castOther = ( EvaluerId ) other; 
         
		 return (this.getCodeoccs()==castOther.getCodeoccs())
 && (this.getCodecli()==castOther.getCodecli());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCodeoccs();
         result = 37 * result + this.getCodecli();
         return result;
   }   


}


