package Mapping;
// Generated 8 févr. 2020 15:26:40 by Hibernate Tools 4.3.1

import java.util.Objects;




/**
 * ExecuterCircuit generated by hbm2java
 */
public class ExecuterCircuit  implements java.io.Serializable {


     private ExecuterCircuitId id;
     private Circuit circuit;
     private Client client;
     private OccurrenceS occurrenceS;
     private Double repetimin;
     private Double repetimax;
     private Double tempsrecup;

    public ExecuterCircuit() {
    }

	
    public ExecuterCircuit(ExecuterCircuitId id, Circuit circuit, Client client, OccurrenceS occurrenceS) {
        this.id = id;
        this.circuit = circuit;
        this.client = client;
        this.occurrenceS = occurrenceS;
    }
    public ExecuterCircuit(ExecuterCircuitId id, Circuit circuit, Client client, OccurrenceS occurrenceS, Double repetimin, Double repetimax, Double tempsrecup) {
       this.id = id;
       this.circuit = circuit;
       this.client = client;
       this.occurrenceS = occurrenceS;
       this.repetimin = repetimin;
       this.repetimax = repetimax;
       this.tempsrecup = tempsrecup;
    }
   
    public ExecuterCircuitId getId() {
        return this.id;
    }
    
    public void setId(ExecuterCircuitId id) {
        this.id = id;
    }
    public Circuit getCircuit() {
        return this.circuit;
    }
    
    public void setCircuit(Circuit circuit) {
        this.circuit = circuit;
    }
    public Client getClient() {
        return this.client;
    }
    
    public void setClient(Client client) {
        this.client = client;
    }
    public OccurrenceS getOccurrenceS() {
        return this.occurrenceS;
    }
    
    public void setOccurrenceS(OccurrenceS occurrenceS) {
        this.occurrenceS = occurrenceS;
    }
    public Double getRepetimin() {
        return this.repetimin;
    }
    
    public void setRepetimin(Double repetimin) {
        this.repetimin = repetimin;
    }
    public Double getRepetimax() {
        return this.repetimax;
    }
    
    public void setRepetimax(Double repetimax) {
        this.repetimax = repetimax;
    }
    public Double getTempsrecup() {
        return this.tempsrecup;
    }
    
    public void setTempsrecup(Double tempsrecup) {
        this.tempsrecup = tempsrecup;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 17 * hash + Objects.hashCode(this.id);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final ExecuterCircuit other = (ExecuterCircuit) obj;
        if (!Objects.equals(this.id, other.id)) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "ExecuterCircuit{" + "id=" + id + ", circuit=" + circuit + ", client=" + client + ", occurrenceS=" + occurrenceS + ", repetimin=" + repetimin + ", repetimax=" + repetimax + ", tempsrecup=" + tempsrecup + '}';
    }

    
}


