package Mapping;
// Generated 8 févr. 2020 15:26:40 by Hibernate Tools 4.3.1



/**
 * ExecuterExo generated by hbm2java
 */
public class ExecuterExo  implements java.io.Serializable {


     private ExecuterExoId id;
     private Client client;
     private Exercice exercice;
     private OccurrenceS occurrenceS;
     private Integer duree;
     private Integer serie;
     private Integer repetitionexo;
     private Double distance;
     private Integer ordre;
     private Double dureedem;
     private Integer seriedem;
     private Integer repdem;
     private Double distdem;

    public ExecuterExo() {
    }

	
    public ExecuterExo(ExecuterExoId id, Client client, Exercice exercice, OccurrenceS occurrenceS) {
        this.id = id;
        this.client = client;
        this.exercice = exercice;
        this.occurrenceS = occurrenceS;
    }
    public ExecuterExo(ExecuterExoId id, Client client, Exercice exercice, OccurrenceS occurrenceS, Integer duree, Integer serie, Integer repetitionexo, Double distance, Integer ordre, Double dureedem, Integer seriedem, Integer repdem, Double distdem) {
       this.id = id;
       this.client = client;
       this.exercice = exercice;
       this.occurrenceS = occurrenceS;
       this.duree = duree;
       this.serie = serie;
       this.repetitionexo = repetitionexo;
       this.distance = distance;
       this.ordre = ordre;
       this.dureedem = dureedem;
       this.seriedem = seriedem;
       this.repdem = repdem;
       this.distdem = distdem;
    }
   
    public ExecuterExoId getId() {
        return this.id;
    }
    
    public void setId(ExecuterExoId id) {
        this.id = id;
    }
    public Client getClient() {
        return this.client;
    }
    
    public void setClient(Client client) {
        this.client = client;
    }
    public Exercice getExercice() {
        return this.exercice;
    }
    
    public void setExercice(Exercice exercice) {
        this.exercice = exercice;
    }
    public OccurrenceS getOccurrenceS() {
        return this.occurrenceS;
    }
    
    public void setOccurrenceS(OccurrenceS occurrenceS) {
        this.occurrenceS = occurrenceS;
    }
    public Integer getDuree() {
        return this.duree;
    }
    
    public void setDuree(Integer duree) {
        this.duree = duree;
    }
    public Integer getSerie() {
        return this.serie;
    }
    
    public void setSerie(Integer serie) {
        this.serie = serie;
    }
    public Integer getRepetitionexo() {
        return this.repetitionexo;
    }
    
    public void setRepetitionexo(Integer repetitionexo) {
        this.repetitionexo = repetitionexo;
    }
    public Double getDistance() {
        return this.distance;
    }
    
    public void setDistance(Double distance) {
        this.distance = distance;
    }
    public Integer getOrdre() {
        return this.ordre;
    }
    
    public void setOrdre(Integer ordre) {
        this.ordre = ordre;
    }
    public Double getDureedem() {
        return this.dureedem;
    }
    
    public void setDureedem(Double dureedem) {
        this.dureedem = dureedem;
    }
    public Integer getSeriedem() {
        return this.seriedem;
    }
    
    public void setSeriedem(Integer seriedem) {
        this.seriedem = seriedem;
    }
    public Integer getRepdem() {
        return this.repdem;
    }
    
    public void setRepdem(Integer repdem) {
        this.repdem = repdem;
    }
    public Double getDistdem() {
        return this.distdem;
    }
    
    public void setDistdem(Double distdem) {
        this.distdem = distdem;
    }


 @Override
    public int hashCode() {
        return super.hashCode(); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public boolean equals(Object obj) {
        return super.equals(obj); //To change body of generated methods, choose Tools | Templates.
    }
   


}


