package Mapping;
// Generated 8 févr. 2020 15:26:40 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * NotifierId generated by hbm2java
 */
public class NotifierId  implements java.io.Serializable {


     private int iduserSender;
     private int iduserReceiver;
     private Date datenotif;

    public NotifierId() {
    }

    public NotifierId(int iduserSender, int iduserReceiver, Date datenotif) {
       this.iduserSender = iduserSender;
       this.iduserReceiver = iduserReceiver;
       this.datenotif = datenotif;
    }
   
    public int getIduserSender() {
        return this.iduserSender;
    }
    
    public void setIduserSender(int iduserSender) {
        this.iduserSender = iduserSender;
    }
    public int getIduserReceiver() {
        return this.iduserReceiver;
    }
    
    public void setIduserReceiver(int iduserReceiver) {
        this.iduserReceiver = iduserReceiver;
    }
    public Date getDatenotif() {
        return this.datenotif;
    }
    
    public void setDatenotif(Date datenotif) {
        this.datenotif = datenotif;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof NotifierId) ) return false;
		 NotifierId castOther = ( NotifierId ) other; 
         
		 return (this.getIduserSender()==castOther.getIduserSender())
 && (this.getIduserReceiver()==castOther.getIduserReceiver())
 && ( (this.getDatenotif()==castOther.getDatenotif()) || ( this.getDatenotif()!=null && castOther.getDatenotif()!=null && this.getDatenotif().equals(castOther.getDatenotif()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIduserSender();
         result = 37 * result + this.getIduserReceiver();
         result = 37 * result + ( getDatenotif() == null ? 0 : this.getDatenotif().hashCode() );
         return result;
   }   


}


