package Mapping;
// Generated 8 févr. 2020 15:26:40 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Notifier generated by hbm2java
 */
public class Notifier implements java.io.Serializable {

    private NotifierId id;
    private User userByIduserSender;
    private User userByIduserReceiver;
    private String message;
    private Date datenotif;

    public Notifier() {
    }

    public Notifier(NotifierId id, User userByIduserSender, User userByIduserReceiver) {
        this.id = id;
        this.userByIduserSender = userByIduserSender;
        this.userByIduserReceiver = userByIduserReceiver;
    }

    public Notifier(NotifierId id, User userByIduserSender, User userByIduserReceiver, String message) {
        this.id = id;
        this.userByIduserSender = userByIduserSender;
        this.userByIduserReceiver = userByIduserReceiver;
        this.message = message;
    }
    
        public Date getDatenotif() {
        return this.datenotif;
    }
    
    public void setDatenotif(Date datenotif) {
        this.datenotif = datenotif;
    }

    public NotifierId getId() {
        return this.id;
    }

    public void setId(NotifierId id) {
        this.id = id;
    }

    public User getUserByIduserSender() {
        return this.userByIduserSender;
    }

    public void setUserByIduserSender(User userByIduserSender) {
        this.userByIduserSender = userByIduserSender;
    }

    public User getUserByIduserReceiver() {
        return this.userByIduserReceiver;
    }

    public void setUserByIduserReceiver(User userByIduserReceiver) {
        this.userByIduserReceiver = userByIduserReceiver;
    }

    public String getMessage() {
        return this.message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    @Override
    public int hashCode() {
        return super.hashCode(); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public boolean equals(Object obj) {
        return super.equals(obj); //To change body of generated methods, choose Tools | Templates.
    }

}
