package Mapping;
// Generated 8 févr. 2020 15:26:40 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Profil generated by hbm2java
 */
public class Profil  implements java.io.Serializable {


     private Integer codeprof;
     private String nomprof;
     private Set programmes = new HashSet(0);
     private Set clients = new HashSet(0);

    public Profil() {
    }

    public Profil(String nomprof, Set programmes, Set clients) {
       this.nomprof = nomprof;
       this.programmes = programmes;
       this.clients = clients;
    }
   
    public Integer getCodeprof() {
        return this.codeprof;
    }
    
    public void setCodeprof(Integer codeprof) {
        this.codeprof = codeprof;
    }
    public String getNomprof() {
        return this.nomprof;
    }
    
    public void setNomprof(String nomprof) {
        this.nomprof = nomprof;
    }
    public Set getProgrammes() {
        return this.programmes;
    }
    
    public void setProgrammes(Set programmes) {
        this.programmes = programmes;
    }
    public Set getClients() {
        return this.clients;
    }
    
    public void setClients(Set clients) {
        this.clients = clients;
    }


 @Override
    public int hashCode() {
        return super.hashCode(); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public boolean equals(Object obj) {
        return super.equals(obj); //To change body of generated methods, choose Tools | Templates.
    }

}


