package Mapping;
// Generated 8 févr. 2020 15:26:40 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer iduser;
     private String loginuser;
     private String passworduser;
     private Set coaches = new HashSet(0);
     private Set notifiersForIduserSender = new HashSet(0);
     private Set notifiersForIduserReceiver = new HashSet(0);
     private Set clients = new HashSet(0);

    public User() {
    }

    public User(String loginuser, String passworduser, Set coaches, Set notifiersForIduserSender, Set notifiersForIduserReceiver, Set clients) {
       this.loginuser = loginuser;
       this.passworduser = passworduser;
       this.coaches = coaches;
       this.notifiersForIduserSender = notifiersForIduserSender;
       this.notifiersForIduserReceiver = notifiersForIduserReceiver;
       this.clients = clients;
    }
   
    public Integer getIduser() {
        return this.iduser;
    }
    
    public void setIduser(Integer iduser) {
        this.iduser = iduser;
    }
    public String getLoginuser() {
        return this.loginuser;
    }
    
    public void setLoginuser(String loginuser) {
        this.loginuser = loginuser;
    }
    public String getPassworduser() {
        return this.passworduser;
    }
    
    public void setPassworduser(String passworduser) {
        this.passworduser = passworduser;
    }
    public Set getCoaches() {
        return this.coaches;
    }
    
    public void setCoaches(Set coaches) {
        this.coaches = coaches;
    }
    public Set getNotifiersForIduserSender() {
        return this.notifiersForIduserSender;
    }
    
    public void setNotifiersForIduserSender(Set notifiersForIduserSender) {
        this.notifiersForIduserSender = notifiersForIduserSender;
    }
    public Set getNotifiersForIduserReceiver() {
        return this.notifiersForIduserReceiver;
    }
    
    public void setNotifiersForIduserReceiver(Set notifiersForIduserReceiver) {
        this.notifiersForIduserReceiver = notifiersForIduserReceiver;
    }
    public Set getClients() {
        return this.clients;
    }
    
    public void setClients(Set clients) {
        this.clients = clients;
    }
 @Override
    public int hashCode() {
        return super.hashCode(); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public boolean equals(Object obj) {
        return super.equals(obj); //To change body of generated methods, choose Tools | Templates.
    }



}


